version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            docker build --rm=false -t "keepnetwork/nodejs-python-solc:$CIRCLE_BUILD_NUM" .
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker push "keepnetwork/nodejs-python-solc:$CIRCLE_BUILD_NUM"
workflows:
  version: 2
  push-image:
    jobs:
      - build:
          context: docker-hub
